version: "3"
services:
  web-app:
    build:
      context: ./ # Dockerfile path
      dockerfile: ./docker/construct_app/Dockerfile # Dockerfile name
    image: intrapps_web_image:0.6.16-rel # image name
    container_name: intrapps_web_container # container name
    ports:
      - "3000:3000"
    environment: # Environment variable
      - PORT=3000
    volumes: # mount workdir
      - ./logs:/root/.npm/_logs
      - ./app/src/common/config:/work/common/config
      - ./logs:/work/logs
    command: [sh, -c, npm install && npm start] # Command after working
    expose: # Open port settting
      - "3000"
    networks:
      - intrapps_network
  # Nginx
  nginx-web-proxy:
    build:
      context: ./ # Dockerfile path
      dockerfile: ./docker/construct_web/Dockerfile # Dockerfile name
    image: intrapps_web_nginx_image:0.3.0-rel # image name
    container_name: intrapps_web_nginx_container # container name
    ports: # Port in this application(host:container)
      - 443:443
    volumes: # mount workdir
      - ./web/app/nginx:/etc/nginx/conf.d/
      - ./app/nginx:/etc/ssl/certs
    links:
      - "web-app"
    expose: # Open port settting
      - "443"
    networks:
      - intrapps_network
networks:
  intrapps_network:
    external: true
